In [ ]:
# %pip install --no-cache-dir git+https://github.com/khanh-at-gex/gex-msgraph.git python-dotenv

In [1]:
# Import necessary libraries
from dotenv import load_dotenv; load_dotenv()
from gex_msgraph import GraphClient, FileItem

In [2]:
ROOT_DIR = r"2026\Project Phoenix\04. Working files"

In [4]:
client = GraphClient("das_u1")
await client.__aenter__()

items = await client.list_files(ROOT_DIR)
print(f"Connected. Found {len(items)} items at the drive root.")

Connected. Found 27 items at the drive root.

In [10]:
xlsx_files = await client.walk(ROOT_DIR, pattern="*.xls*")
xlsx_files = sorted(xlsx_files, key=lambda f: f.path)
print(f"Found {len(xlsx_files)} .xlsx files recursively")
for f in xlsx_files:
    print(" ", f.path)

Found 23 .xlsx files recursively
  2026/Project Phoenix/04. Working files/00. Template/template_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/03. CADIVI/KH_CADIVI_5Y_29Apr2026.xlsx
  2026/Project Phoenix/04. Working files/05. THI/KH_THIBIDI_5Y_29Apr2026.xlsm
  2026/Project Phoenix/04. Working files/06. MEE/[MEE]_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/07. HEM/[HEM]_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/08. EMIC/[EMIC]_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/09. CFT/KH_CFT_5Y_29Apr2026.xlsx
  2026/Project Phoenix/04. Working files/10. Phatdien/Phatdien_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/11. GETC/GETCHY_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/11. GETC/GETC_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/12. GELEXTECH/GELEXTECH_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/13. GELEXINVEST/GELEXINVEST_CFForecast_2026_2030.xlsx
  2026/Project Phoenix/04. Working files/14. GEL/[GEL]_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/15. VGC/KH_VGC_CF me 2026-2030_form riêng.xlsx
  2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_04.5.26.xlsm
  2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_29.4.26.xlsm
  2026/Project Phoenix/04. Working files/17. PXL/KH_PXL_5Y_2.xlsx
  2026/Project Phoenix/04. Working files/18. FIH/Citynest_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/18. FIH/Kim Trang_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/18. FIH/Landora_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/20. WADACO/KH_WADACO_CF_5Y_29.4.26.xlsm
  2026/Project Phoenix/04. Working files/21. TitanCorp/Titan Corp_CFForecast_2026_2030.xlsm
  2026/Project Phoenix/04. Working files/24. TTP/[TTP]_CFForecast_2026_2030.xlsm

In [11]:
pd.DataFrame(xlsx_files)

,name,path,id,size,modified,is_folder
0,template_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/00. Template/template_CFForecast_2026_2030.xlsm,01AF4VZGOUV6BALEKO3ZGKTFEBY5WWLYMZ,125407,2026-05-04 07:37:39+00:00,False
1,KH_CADIVI_5Y_29Apr2026.xlsx,2026/Project Phoenix/04. Working files/03. CADIVI/KH_CADIVI_5Y_29Apr2026.xlsx,01AF4VZGMYBDXSXVEJZBB2PKYE2QU735BF,511826,2026-05-04 05:51:35+00:00,False
2,KH_THIBIDI_5Y_29Apr2026.xlsm,2026/Project Phoenix/04. Working files/05. THI/KH_THIBIDI_5Y_29Apr2026.xlsm,01AF4VZGKOAWGL3VOVFZGYWDJZ3T26HCQE,672372,2026-04-29 10:38:01+00:00,False
3,[MEE]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/06. MEE/[MEE]_CFForecast_2026_2030.xlsx,01AF4VZGN4DU4GB5SFF5DJYEDP7ASRB4G6,622714,2026-05-04 01:36:02+00:00,False
4,[HEM]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/07. HEM/[HEM]_CFForecast_2026_2030.xlsx,01AF4VZGLXU6UZEKBLJNHLCIQ6FV7IGJWI,585154,2026-04-29 08:45:56+00:00,False
5,[EMIC]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/08. EMIC/[EMIC]_CFForecast_2026_2030.xlsx,01AF4VZGJNILTDWM3R3RHLOTSOAQ6QVUCE,783489,2026-05-04 06:04:29+00:00,False
6,KH_CFT_5Y_29Apr2026.xlsx,2026/Project Phoenix/04. Working files/09. CFT/KH_CFT_5Y_29Apr2026.xlsx,01AF4VZGKFWQ2GWKGF5FE355PU6WDIAH2J,292763,2026-05-04 02:52:32+00:00,False
7,Phatdien_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/10. Phatdien/Phatdien_CFForecast_2026_2030.xlsx,01AF4VZGJPSIHL3XTN3BGLQRHPSINHPPD4,221777,2026-04-29 08:41:16+00:00,False
8,GETCHY_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/11. GETC/GETCHY_CFForecast_2026_2030.xlsx,01AF4VZGPUYA27RIYAGFGYMY7YD4XTWTM4,347508,2026-04-29 08:45:43+00:00,False
9,GETC_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/11. GETC/GETC_CFForecast_2026_2030.xlsx,01AF4VZGNYCTBBPDNZJBE2GXI3ZGLZR5X3,354844,2026-04-29 08:52:42+00:00,False
10,GELEXTECH_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/12. GELEXTECH/GELEXTECH_CFForecast_2026_2030.xlsx,01AF4VZGPPGOW7HENAUJD3BB5XT6OVBBLW,217180,2026-04-29 08:41:37+00:00,False
11,GELEXINVEST_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/13. GELEXINVEST/GELEXINVEST_CFForecast_2026_2030.xlsx,01AF4VZGJECLGZGFMOTZHKUTBFVLTK4TNM,214784,2026-05-01 11:53:44+00:00,False
12,[GEL]_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/14. GEL/[GEL]_CFForecast_2026_2030.xlsm,01AF4VZGIE6LPHPOBNURAKYSBLAAUMJHLE,629487,2026-04-30 03:11:47+00:00,False
13,KH_VGC_CF me 2026-2030_form riêng.xlsx,2026/Project Phoenix/04. Working files/15. VGC/KH_VGC_CF me 2026-2030_form riêng.xlsx,01AF4VZGN7YCPQSRNDMFD2J3NXBFD2A4LC,2143549,2026-04-29 02:51:38+00:00,False
14,KH_Viwasupco_CF_5Y_04.5.26.xlsm,2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_04.5.26.xlsm,01AF4VZGJ74FUHHJTM4VAIRVPG2A4QH755,1858589,2026-05-04 04:06:52+00:00,False
15,KH_Viwasupco_CF_5Y_29.4.26.xlsm,2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_29.4.26.xlsm,01AF4VZGIOQFN24X22LZB36NL3VQE274RV,913553,2026-04-29 16:43:40+00:00,False
16,KH_PXL_5Y_2.xlsx,2026/Project Phoenix/04. Working files/17. PXL/KH_PXL_5Y_2.xlsx,01AF4VZGKFPTQO2PUWD5C3NGYK7IXWMZYD,290977,2026-05-03 15:46:32+00:00,False
17,Citynest_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Citynest_CFForecast_2026_2030.xlsm,01AF4VZGPCRDOGLXKCVFEI5BOKMLWVQL5Z,2353329,2026-04-29 08:35:25+00:00,False
18,Kim Trang_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Kim Trang_CFForecast_2026_2030.xlsm,01AF4VZGMXRP4NRNNGPNELWB6BOVKPMRBN,2464193,2026-04-29 08:35:20+00:00,False
19,Landora_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Landora_CFForecast_2026_2030.xlsm,01AF4VZGNTZKXNCKT6TJAYYABIGYU6PKUX,2498671,2026-04-29 08:35:32+00:00,False
20,KH_WADACO_CF_5Y_29.4.26.xlsm,2026/Project Phoenix/04. Working files/20. WADACO/KH_WADACO_CF_5Y_29.4.26.xlsm,01AF4VZGIDF2375MR2VZDKWGFR45ICKLWG,871416,2026-04-30 03:20:02+00:00,False
21,Titan Corp_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/21. TitanCorp/Titan Corp_CFForecast_2026_2030.xlsm,01AF4VZGJCOTZMKMKNOREIIB5PVZIXLIR5,8412245,2026-04-29 08:35:04+00:00,False
22,[TTP]_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/24. TTP/[TTP]_CFForecast_2026_2030.xlsm,01AF4VZGPUD4L3AVYXPFGJWWPFLPRGD46Q,503222,2026-05-04 01:45:01+00:00,False

In [12]:
items = await client.list_files(ROOT_DIR)
for item in items:
    label = "(folder)" if item.is_folder else f"{item.size:,} bytes"
    print(item.name, label)

00. support data (folder)
00. Template (folder)
01. GELEX (folder)
02. GEE (folder)
03. CADIVI (folder)
04. CMB (folder)
05. THI (folder)
06. MEE (folder)
07. HEM (folder)
08. EMIC (folder)
09. CFT (folder)
10. Phatdien (folder)
11. GETC (folder)
12. GELEXTECH (folder)
13. GELEXINVEST (folder)
14. GEL (folder)
15. VGC (folder)
16. Viwasupco (folder)
17. PXL (folder)
18. FIH (folder)
19. TITANHP (folder)
20. WADACO (folder)
21. TitanCorp (folder)
22. BSG1 (folder)
23. BSG2 (folder)
24. TTP (folder)
25. EIB (folder)

In [26]:
items = await client.list_files(ROOT_DIR)
pd.DataFrame(items)

,name,path,id,size,modified,is_folder
0,00. support data,2026/Project Phoenix/04. Working files/00. support data,01AF4VZGNWCQSIZNY7NJF22EM3KCDDVXRJ,0,2026-04-28 02:27:56+00:00,True
1,00. Template,2026/Project Phoenix/04. Working files/00. Template,01AF4VZGLQSQ346SV7PJDLDFC3RWG3F6T3,125407,2026-04-24 07:13:06+00:00,True
2,01. GELEX,2026/Project Phoenix/04. Working files/01. GELEX,01AF4VZGJMSVPHXYRCDFFYS4RX5HZWCDGV,0,2026-04-28 01:32:08+00:00,True
3,02. GEE,2026/Project Phoenix/04. Working files/02. GEE,01AF4VZGMS32YL6DVJGBCY4AXKROETC3VZ,0,2026-04-28 01:32:08+00:00,True
4,03. CADIVI,2026/Project Phoenix/04. Working files/03. CADIVI,01AF4VZGL4DMQQEKSACBAK2SBZJDN4ZKKZ,511826,2026-04-28 01:32:08+00:00,True
5,04. CMB,2026/Project Phoenix/04. Working files/04. CMB,01AF4VZGIRMZ5D4DM4NBGYPBLIJOZIVZEA,0,2026-04-28 01:32:08+00:00,True
6,05. THI,2026/Project Phoenix/04. Working files/05. THI,01AF4VZGMF5YW7XKYAXNGY4XT5NBONM5XB,672372,2026-04-28 01:32:08+00:00,True
7,06. MEE,2026/Project Phoenix/04. Working files/06. MEE,01AF4VZGMXI7LILK3IKRAJ7RR2NF77KIPQ,622714,2026-04-28 01:32:08+00:00,True
8,07. HEM,2026/Project Phoenix/04. Working files/07. HEM,01AF4VZGNMMKSF4P4OJ5AJM3UUDUL73VH5,585154,2026-04-28 01:32:08+00:00,True
9,08. EMIC,2026/Project Phoenix/04. Working files/08. EMIC,01AF4VZGKWXBL7IUC5LRCJBXJF4Y2PKA2G,783489,2026-04-28 01:32:08+00:00,True
10,09. CFT,2026/Project Phoenix/04. Working files/09. CFT,01AF4VZGLG3BBAX47KHFAZO42EN6JFXJCX,292763,2026-04-28 01:32:08+00:00,True
11,10. Phatdien,2026/Project Phoenix/04. Working files/10. Phatdien,01AF4VZGKL2PX35F6GAFHIGW7UMFRAEN4R,221777,2026-04-28 01:32:08+00:00,True
12,11. GETC,2026/Project Phoenix/04. Working files/11. GETC,01AF4VZGPKZBZGWJYYFRDJPTT65LMUJLFO,702352,2026-04-28 01:32:08+00:00,True
13,12. GELEXTECH,2026/Project Phoenix/04. Working files/12. GELEXTECH,01AF4VZGKE7UGEBUTDDBHIZBVOGO6KJ4I5,217180,2026-04-28 01:32:08+00:00,True
14,13. GELEXINVEST,2026/Project Phoenix/04. Working files/13. GELEXINVEST,01AF4VZGIWQBLFZ7ZIFJB3IMGH2FUNV7ZH,214784,2026-04-28 01:32:08+00:00,True
15,14. GEL,2026/Project Phoenix/04. Working files/14. GEL,01AF4VZGOP72FY5CJPX5D2ILPKH76IVBNJ,629487,2026-04-28 01:32:08+00:00,True
16,15. VGC,2026/Project Phoenix/04. Working files/15. VGC,01AF4VZGJ4VCU7EERZSNDIESNEQCLA6PTE,2143549,2026-04-28 01:32:08+00:00,True
17,16. Viwasupco,2026/Project Phoenix/04. Working files/16. Viwasupco,01AF4VZGIGH7P2CSOM45CZRBISEC2VMSI3,2772142,2026-04-28 01:32:08+00:00,True
18,17. PXL,2026/Project Phoenix/04. Working files/17. PXL,01AF4VZGJOLOXQ2VZNPNGKQA5CC7WQWGMB,290977,2026-04-28 01:32:08+00:00,True
19,18. FIH,2026/Project Phoenix/04. Working files/18. FIH,01AF4VZGJ4IWDQ2YUCZBAKZ54OKE3LKD5X,7316193,2026-04-28 01:32:08+00:00,True
20,19. TITANHP,2026/Project Phoenix/04. Working files/19. TITANHP,01AF4VZGNW2OD4VDBX4BHJ7RZSOVNOZYYS,0,2026-04-28 01:32:08+00:00,True
21,20. WADACO,2026/Project Phoenix/04. Working files/20. WADACO,01AF4VZGLBH4VZ7AVYJRF2C7MBTMD7RE7O,871416,2026-04-28 01:32:08+00:00,True
22,21. TitanCorp,2026/Project Phoenix/04. Working files/21. TitanCorp,01AF4VZGLWF2QIPXFLBRE2MQVRUJT4FAB2,8412245,2026-04-28 01:32:08+00:00,True
23,22. BSG1,2026/Project Phoenix/04. Working files/22. BSG1,01AF4VZGNCWFK6DCD2W5BIEMSHHYIFLE7T,0,2026-04-28 01:32:08+00:00,True
24,23. BSG2,2026/Project Phoenix/04. Working files/23. BSG2,01AF4VZGNJJ6G2TCQ4UBC3QSGDSDZMIPDD,0,2026-04-28 01:32:08+00:00,True
25,24. TTP,2026/Project Phoenix/04. Working files/24. TTP,01AF4VZGINAWNW45424ZDYA7FEOB6B3XYN,503222,2026-04-28 01:32:08+00:00,True
26,25. EIB,2026/Project Phoenix/04. Working files/25. EIB,01AF4VZGJM4Q4ERQVLBRBL6DAOVI5I5XWT,0,2026-04-28 01:32:08+00:00,True

In [33]:
import pandas as pd

# 1. All folders (relative to ROOT_DIR)
items = await client.list_files(ROOT_DIR)
df_folders = pd.DataFrame(items)[["name", "path"]].rename(columns={"name": "folder_name", "path": "folder_path"})
# df_folders

# 2. All .xlsx files (relative to ROOT_DIR)
xlsx_files = await client.walk(ROOT_DIR, pattern="*.xls*")
df_xlsx = pd.DataFrame(xlsx_files)[["name", "path", "modified"]].rename(columns={"name": "file_name", "path": "file_path", "modified": "file_modified"})
df_xlsx["folder_path"] = df_xlsx["file_path"].apply(
    lambda p: strip_root(p.rsplit("/", 1)[0]) if "/" in p else ""
)
# df_xlsx

df = df_folders.merge(df_xlsx, on="folder_path", how="left")
display(df[~df["folder_name"].str.startswith("00")])

,folder_name,folder_path,file_name,file_path,file_modified
2,01. GELEX,2026/Project Phoenix/04. Working files/01. GELEX,NaN,NaN,NaT
3,02. GEE,2026/Project Phoenix/04. Working files/02. GEE,NaN,NaN,NaT
4,03. CADIVI,2026/Project Phoenix/04. Working files/03. CADIVI,KH_CADIVI_5Y_29Apr2026.xlsx,2026/Project Phoenix/04. Working files/03. CADIVI/KH_CADIVI_5Y_29Apr2026.xlsx,2026-05-04 05:51:35+00:00
5,04. CMB,2026/Project Phoenix/04. Working files/04. CMB,NaN,NaN,NaT
6,05. THI,2026/Project Phoenix/04. Working files/05. THI,KH_THIBIDI_5Y_29Apr2026.xlsm,2026/Project Phoenix/04. Working files/05. THI/KH_THIBIDI_5Y_29Apr2026.xlsm,2026-04-29 10:38:01+00:00
7,06. MEE,2026/Project Phoenix/04. Working files/06. MEE,[MEE]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/06. MEE/[MEE]_CFForecast_2026_2030.xlsx,2026-05-04 01:36:02+00:00
8,07. HEM,2026/Project Phoenix/04. Working files/07. HEM,[HEM]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/07. HEM/[HEM]_CFForecast_2026_2030.xlsx,2026-04-29 08:45:56+00:00
9,08. EMIC,2026/Project Phoenix/04. Working files/08. EMIC,[EMIC]_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/08. EMIC/[EMIC]_CFForecast_2026_2030.xlsx,2026-05-04 06:04:29+00:00
10,09. CFT,2026/Project Phoenix/04. Working files/09. CFT,KH_CFT_5Y_29Apr2026.xlsx,2026/Project Phoenix/04. Working files/09. CFT/KH_CFT_5Y_29Apr2026.xlsx,2026-05-04 02:52:32+00:00
11,10. Phatdien,2026/Project Phoenix/04. Working files/10. Phatdien,Phatdien_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/10. Phatdien/Phatdien_CFForecast_2026_2030.xlsx,2026-04-29 08:41:16+00:00
12,11. GETC,2026/Project Phoenix/04. Working files/11. GETC,GETC_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/11. GETC/GETC_CFForecast_2026_2030.xlsx,2026-04-29 08:52:42+00:00
13,11. GETC,2026/Project Phoenix/04. Working files/11. GETC,GETCHY_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/11. GETC/GETCHY_CFForecast_2026_2030.xlsx,2026-04-29 08:45:43+00:00
14,12. GELEXTECH,2026/Project Phoenix/04. Working files/12. GELEXTECH,GELEXTECH_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/12. GELEXTECH/GELEXTECH_CFForecast_2026_2030.xlsx,2026-04-29 08:41:37+00:00
15,13. GELEXINVEST,2026/Project Phoenix/04. Working files/13. GELEXINVEST,GELEXINVEST_CFForecast_2026_2030.xlsx,2026/Project Phoenix/04. Working files/13. GELEXINVEST/GELEXINVEST_CFForecast_2026_2030.xlsx,2026-05-01 11:53:44+00:00
16,14. GEL,2026/Project Phoenix/04. Working files/14. GEL,[GEL]_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/14. GEL/[GEL]_CFForecast_2026_2030.xlsm,2026-04-30 03:11:47+00:00
17,15. VGC,2026/Project Phoenix/04. Working files/15. VGC,KH_VGC_CF me 2026-2030_form riêng.xlsx,2026/Project Phoenix/04. Working files/15. VGC/KH_VGC_CF me 2026-2030_form riêng.xlsx,2026-04-29 02:51:38+00:00
18,16. Viwasupco,2026/Project Phoenix/04. Working files/16. Viwasupco,KH_Viwasupco_CF_5Y_04.5.26.xlsm,2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_04.5.26.xlsm,2026-05-04 04:06:52+00:00
19,16. Viwasupco,2026/Project Phoenix/04. Working files/16. Viwasupco,KH_Viwasupco_CF_5Y_29.4.26.xlsm,2026/Project Phoenix/04. Working files/16. Viwasupco/KH_Viwasupco_CF_5Y_29.4.26.xlsm,2026-04-29 16:43:40+00:00
20,17. PXL,2026/Project Phoenix/04. Working files/17. PXL,KH_PXL_5Y_2.xlsx,2026/Project Phoenix/04. Working files/17. PXL/KH_PXL_5Y_2.xlsx,2026-05-03 15:46:32+00:00
21,18. FIH,2026/Project Phoenix/04. Working files/18. FIH,Citynest_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Citynest_CFForecast_2026_2030.xlsm,2026-04-29 08:35:25+00:00
22,18. FIH,2026/Project Phoenix/04. Working files/18. FIH,Kim Trang_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Kim Trang_CFForecast_2026_2030.xlsm,2026-04-29 08:35:20+00:00
23,18. FIH,2026/Project Phoenix/04. Working files/18. FIH,Landora_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/18. FIH/Landora_CFForecast_2026_2030.xlsm,2026-04-29 08:35:32+00:00
24,19. TITANHP,2026/Project Phoenix/04. Working files/19. TITANHP,NaN,NaN,NaT
25,20. WADACO,2026/Project Phoenix/04. Working files/20. WADACO,KH_WADACO_CF_5Y_29.4.26.xlsm,2026/Project Phoenix/04. Working files/20. WADACO/KH_WADACO_CF_5Y_29.4.26.xlsm,2026-04-30 03:20:02+00:00
26,21. TitanCorp,2026/Project Phoenix/04. Working files/21. TitanCorp,Titan Corp_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/21. TitanCorp/Titan Corp_CFForecast_2026_2030.xlsm,2026-04-29 08:35:04+00:00
27,22. BSG1,2026/Project Phoenix/04. Working files/22. BSG1,NaN,NaN,NaT
28,23. BSG2,2026/Project Phoenix/04. Working files/23. BSG2,NaN,NaN,NaT
29,24. TTP,2026/Project Phoenix/04. Working files/24. TTP,[TTP]_CFForecast_2026_2030.xlsm,2026/Project Phoenix/04. Working files/24. TTP/[TTP]_CFForecast_2026_2030.xlsm,2026-05-04 01:45:01+00:00
30,25. EIB,2026/Project Phoenix/04. Working files/25. EIB,NaN,NaN,NaT